main_config:
  dry_run: False
  log_level: INFO
  path_log: "/var/log/submitter/submitter.log"

step:
  translate:
    - DockerAdaptor
    - OccopusAdaptor
    - PkAdaptor
  execute:
    - OccopusAdaptor
    - DockerAdaptor
    - SecurityEnforcerAdaptor
    - PkAdaptor
  update:
    - OccopusAdaptor
    - DockerAdaptor
    - PkAdaptor
  undeploy:
    - PkAdaptor
    - SecurityEnforcerAdaptor
    - DockerAdaptor
    - OccopusAdaptor
  cleanup:
    - DockerAdaptor
    - OccopusAdaptor
    - PkAdaptor

adaptor_config:
 SecurityEnforcerAdaptor:
   types:
     - "tosca.policies.DockerSecretDistribution"
   endpoint: "http://securitypolicymanager:5003/v1.0"
   volume: "/var/lib/submitter/files/output_configs/"

 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endoint: "endpoint"
   volume: "/var/lib/submitter/files/output_configs/"


 OccopusAdaptor:
   types:
     - "tosca.nodes.MiCADO.Occopus.*"
   endoint: "endpoint"
   volume: "/var/lib/submitter/files/output_configs/"


 PkAdaptor:
   types:
     - "tosca.policies.Scaling.MiCADO"
   endpoint: "policykeeper:12345"
   volume: "/var/lib/submitter/files/output_configs/"
